# Thanks to workflow configuration in SagerNet/sing-box
name: Test Docker build

on:
  push:
    paths:
      - "listentt/**"
      - ".github/workflows/test-docker.yml"
  workflow_dispatch:

env:
  REGISTRY_IMAGE: listentt

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PLATFORM_PAIR: ""
    strategy:
      fail-fast: true
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Get commit to build
        id: ref
        run: |-
          ref="${{ github.ref_name }}"
          echo "ref=$ref"
          echo "ref=$ref" >> $GITHUB_OUTPUT
          mkdir -p /tmp/images

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.ref.outputs.ref }}

      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}

      - name: Build
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform }}
          context: .
          tags: |
            ${{ env.REGISTRY_IMAGE }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          outputs: |
            type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=false
            type=tar,dest=/tmp/images/image.tar
          push: false

      - name: Export digest
        run: |
          digest="${{ steps.build.outputs.digest }}"
          echo "Digest: $digest"
          touch "/tmp/images/${digest#sha256:}"

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: image-${{ steps.ref.outputs.ref }}-${{ env.PLATFORM_PAIR }}
          path: /tmp/images/
          compression-level: 9
          if-no-files-found: error
          retention-days: 1
